environ({'PATH': '/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'HOSTNAME': 'ai-conversational-754d4cf796-nlftw', 'LANG': 'C.UTF-8', 'GPG_KEY': '7169605F62C751356D054A26A821E680E5FA6305', 'PYTHON_VERSION': '3.12.10', 'PYTHON_SHA256': '07ab697474595e06f06647417d3c7fa97ded07afc1a7e4454c5639919b46eaea', 'POSTGRES_HOST': 'dev-common-server.postgres.database.azure.com', 'ADA_002_DEPLOYMENT': 'text-data-002', 'API_KEY': 'db8d369a30e840b39ccdfdce4808ec7f', 'GPT_4o_API_VERSION': '2024-08-01-preview', 'SIMILARITY_SEARCH_TOP_K_INTENTS': '30', 'LLM_MAX_TOKENS': '4096', 'RERANKING_TOP_K_FAQS': '5', 'POSTGRES_PASSWORD': 'RBK@123Super$Secure$Pass0Word', 'POSTGRES_PORT': '5432', 'ADA_002_VERSION': '2024-02-01', 'GPT_4o_DEPLOYMENT': 'gpt-4o', 'POSTGRES_SSL': 'require', 'POSTGRES_USERNAME': 'rakbank_dev_postgres_admin_user', 'GPT_4o_MODEL_NAME': 'gpt-4o', 'POSTGRES_DB': 'convo-ai', 'AZURE_ENDPOINT': 'https://rakbankgenaidevai.openai.azure.com', 'LLM_TEMPERATURE': '0.0', 'SYSTEM_PROMPT_PATH': 'prompts/intent_and_faq_matcher.md', 'RERANKING_TOP_K_INTENTS': '5', 'SIMILARITY_SEARCH_TOP_K_FAQS': '30', 'ADA_002_MODEL_NAME': 'text-data-002', 'AI_CONVERSATIONAL_SERVICE_PORT_8000_TCP_PORT': '8000', 'AI_CONVERSATIONAL_SERVICE_PORT_8000_TCP_ADDR': '172.20.160.49', 'AI_CONVERSATIONAL_SERVICE_SERVICE_PORT': '8000', 'AI_CONVERSATIONAL_SERVICE_PORT_8000_TCP_PROTO': 'tcp', 'KUBERNETES_SERVICE_HOST': '172.20.0.1', 'KUBERNETES_SERVICE_PORT': '443', 'KUBERNETES_PORT_443_TCP': 'tcp://172.20.0.1:443', 'AI_CONVERSATIONAL_SERVICE_SERVICE_HOST': '172.20.160.49', 'AI_CONVERSATIONAL_SERVICE_PORT': 'tcp://172.20.160.49:8000', 'KUBERNETES_PORT_443_TCP_PORT': '443', 'AI_CONVERSATIONAL_SERVICE_PORT_8000_TCP': 'tcp://172.20.160.49:8000', 'KUBERNETES_SERVICE_PORT_HTTPS': '443', 'KUBERNETES_PORT_443_TCP_ADDR': '172.20.0.1', 'KUBERNETES_PORT': 'tcp://172.20.0.1:443', 'KUBERNETES_PORT_443_TCP_PROTO': 'tcp', 'HOME': '/root', 'VIRTUAL_ENV': '/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12'})
 Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/lib/python3.12/site-packages/uvicorn/main.py", line 413, in main
    run(
  File "/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/lib/python3.12/site-packages/uvicorn/main.py", line 580, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/lib/python3.12/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/lib/python3.12/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/lib/python3.12/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/lib/python3.12/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/src/ai_conversational_service/app.py", line 15, in <module>
    from src.ai_conversational_service.database import engine, Base
  File "/src/ai_conversational_service/database.py", line 4, in <module>
    from src.ai_conversational_service.config import settings
  File "/src/ai_conversational_service/config.py", line 101, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/lib/python3.12/site-packages/pydantic_settings/main.py", line 176, in __init__
    super().__init__(
  File "/root/.cache/pypoetry/virtualenvs/ai-conversational-service-il7asoJj-py3.12/lib/python3.12/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 13 validation errors for Settings
redis_host
  Field required [type=missing, input_value={'postgres_host': 'dev-co...anking_top_k_faqs': '5'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
redis_port
  Field required [type=missing, input_value={'postgres_host': 'dev-co...anking_top_k_faqs': '5'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
redis_username
  Field required [type=missing, input_value={'postgres_host': 'dev-co...anking_top_k_faqs': '5'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
redis_password
  Field required [type=missing, input_value={'postgres_host': 'dev-co...anking_top_k_faqs': '5'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
redis_db
  Field required [type=missing, input_value={'postgres_host': 'dev-co...anking_top_k_faqs': '5'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
universal_menu_url
  Field required [type=missing, input_value={'postgres_host': 'dev-co...anking_top_k_faqs': '5'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
universal_menu_api_key
  Field required [type=missing, input_value={'postgres_host': 'dev-co...anking_top_k_faqs': '5'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
universal_menu_request_id
  Field required [type=missing, input_value={'postgres_host': 'dev-co...anking_top_k_faqs': '5'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
universal_menu_conversation_id
  Field required [type=missing, input_value={'postgres_host': 'dev-co...anking_top_k_faqs': '5'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
enable_jwt
  Field required [type=missing, input_value={'postgres_host': 'dev-co...anking_top_k_faqs': '5'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
jwt_private_key
  Field required [type=missing, input_value={'postgres_host': 'dev-co...anking_top_k_faqs': '5'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
jwt_algorithm
  Field required [type=missing, input_value={'postgres_host': 'dev-co...anking_top_k_faqs': '5'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
